### ISSUE TITLE
Can you add Domain support & vhost shared Names

### ISSUE THREAD

**Issue by Dexus** [voilab/voilab-express-router#1]
Hey, can you support domains via vhost and let them share about difference apps?

have a portal and a members area, and need to share the links between this vhost's.

Regards,
Josef

**Comment by alexandrevoilab** [comment]
Not sure if I understood your correctly. You have one instance of your app and try to have two subdomains to point on it?

You should use a web server to manage vhosts and set it up as a reverse proxy.
They can be both directed to one instance of your app.

For apache see: https://httpd.apache.org/docs/current/vhosts/
For nginx see: https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/
For the reverse proxy part, google some how to's relevant to your web server of choice.

**Comment by Dexus** [comment]
Hey,

no i use the vhost module for express
but i need to link from one to the other application (vhost/subdomain).

https://github.com/expressjs/vhost

But because of the Router-Class i think its not possible.
I have used before https://github.com/ptcong/express-named-router-url-generator but it has a bad regex so that i cant use it for my needs.

**Comment by alexandrevoilab** [comment]
That's not a use case we plane to support as we do not have a need for it.

That being said, feel free to implement it and open a pull request. If you plan to maintain it, we will gladly merge the pull request.
